import { PGlite } from '@electric-sql/pglite'
import { readFileSync } from 'node:fs'
import assert from 'node:assert/strict'
const db = new PGlite()
await db.exec('create role anon; create role authenticated; create role service_role;')
await db.exec(readFileSync(new URL('../supabase/migrations/20260922120000_init_schema.sql', import.meta.url),'utf8'))
await db.exec(readFileSync(new URL('../supabase/migrations/20260926223000_miembro2_atomicidad.sql', import.meta.url),'utf8'))
await db.exec("insert into usuarios (nombre,correo,password) values ('A','a@test','x'),('B','b@test','x');")
await db.exec("insert into grupos_confianza (usuario_creador_id,nombre) values (1,'Normal');")
assert.equal((await db.query("select count(*)::int n from grupo_miembros where grupo_id=1 and usuario_id=1 and rol='admin'")).rows[0].n,1)
console.log('PASS creación con administrador')
await db.exec(`create function fail_member() returns trigger language plpgsql as $$ begin raise exception 'Fallo simulado'; end $$;
create trigger injected_failure before insert on grupo_miembros for each row execute function fail_member();`)
await assert.rejects(db.exec("insert into grupos_confianza (usuario_creador_id,nombre) values (1,'Debe revertirse')"))
assert.equal((await db.query("select count(*)::int n from grupos_confianza where nombre='Debe revertirse'")).rows[0].n,0)
console.log('PASS rollback completo si falla el administrador')
await db.exec("insert into solicitudes_grupo(grupo_id,usuario_invitado_id,usuario_solicitante_id) values (1,2,1)")
await assert.rejects(db.exec("update solicitudes_grupo set estado='aceptado' where id=1"))
assert.equal((await db.query('select estado from solicitudes_grupo where id=1')).rows[0].estado,'pendiente')
console.log('PASS aceptación fallida conserva solicitud pendiente')
await db.exec('drop trigger injected_failure on grupo_miembros')
await db.exec("update solicitudes_grupo set estado='aceptado' where id=1")
assert.equal((await db.query('select count(*)::int n from grupo_miembros where usuario_id=2')).rows[0].n,1)
await db.exec("update solicitudes_grupo set estado='aceptado' where id=1")
assert.equal((await db.query('select count(*)::int n from grupo_miembros where usuario_id=2')).rows[0].n,1)
console.log('PASS aceptación crea una sola membresía')
await assert.rejects(db.exec("update solicitudes_grupo set estado='rechazado' where id=1"))
console.log('PASS no cambia una solicitud ya respondida')
await db.close()
